---
title: "Data Science Education Dilemmas and Opportunities"
subtitle: ""
author: "Joshua Rosenberg"
date: "2018-10-15"
output:
  xaringan::moon_reader:
    css: ["default", "default-fonts"]
    lib_dir: libs
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

# Background 

- Became interested in how the ‘context’ was characterized in educational technology research - Applied to and began my doctoral program at Michigan State University and started out doing research on context and teachers’ Technological Pedagogical Content Knowledge, or TPACK
- Started to work on a science education research project focused on engaging students in scientific and engineering practices
- Kept my interest in the importance of context by using a research method, the Experience Sampling Method, to study how learners engaged in scientific and engineering practices in a fine-grained way (and how teachers supported this work) and became interested in data science methods
- I was especially interested in how working with data as part of engaging in scientific and engineering practices can be empowering to learners
- Collectively, these experiences led me to my research and teaching in STEM education.

---

# Why data science?

---

# What is data science?

---

# Data science education?


- New field
- Origins:
- Education
    - Data modeling (Lehrer & Romberg, 1996)
    - Statistical reasoning (Wild & Pfannkuch)
    - 

- Statistics
    - Breiman (2001)
    - Donoho (2017)

- Data science practice
    - Lorang (2016)
    - Wickham (2013)
    - Erickson (2017-2018)
    - McNamara (2016)
    - Sean Kross, Roger D Peng, Brian S Caffo, Ira Gooding, Jeffrey T Leek (2017)
    
??? 

The dirty little secret of the ongoing “data science” boom is that most of what people talk about as being data science isn’t what businesses actually need. Businesses need accurate and actionable information to help them make decisions about how they spend their time and resources. There is a very small subset of business problems that are best solved by machine learning; most of them just need good data and an understanding of what it means that is best gained using simple methods.


---

# Not everything 

# Dilemmas and opportunities for data science education

.pull-left[

- Advanced domain
- Not common

]

.pull-right[

- STEM activity
- Empowering

]

---

class: left

# What's not a dilemma?

- Data is everywhere
- Everyone can do data science, even kids as young as those at the Kidergarten level*
- Equity is a first principle

.footnote[[*]see the work of those in New Zealand]

---

class: center

# Dilemma #1: Unplugged vs. with (computational) tools

- 
- R, python, 

---

class: center

# Dilemma #2: Undergraduate and advanced degree vs. K-12

- UTK
- 

---

class: center, middle

# Dilemma #3: Creating data vs. using (and combining) existing data sets

---

class: center, middle

# Dilemma #4: Taught as part of math and science (and other subject matter) courses vs. part of statistics or computer science courses

- In computer science departments


---

class: center

# Dilemma #5: As a entryway to data science, focusing on modeling and visualizing data vs. creating and structuring data

- 
- 

---

class: center

# Dilemma #6: A focus on skills vs. practices

- 
- 

---

class: center

# Dilemma #7: Mastering one (computational) tool vs. learning general principles that (may) transfer

- 
- 

---
class: center

# Dilemma #8: Explanatory vs. predictive models

- 
- 

---

class: center

# Dilemma #9: Resource-intensive tools vs. access

- Chromebook data science
- 

---

class: center

# Dilemma #10: Tools for learning vs. real tools

- CODAP, Fathom, TinkerPlots
- R, Python, Julia

---

# Models: 

- Michelle Wilkerson and colleague's work
- Victor Lee and colleague's work?
- Pratim Sengupta and Satabdi Basu and colleague's work
- Hollylynne Lee
- Lynn Hodge and Joy Bartlett

---

# Opportunities

- Existing curricula
- Lots of attention in industry and at post-secondary level
- Rare area of overlap between math and science standards
- Goal-directed use of engineering and computer science ideas
- Demanding, open-ended, potentially meaningful
- Some strong equity focus among some practitioners
- Not as commercially-oriented as computer science education initiatives

---

# How to proceed

- Do work at the K-12 level<sup>1</sup>
- Use existing curricula
- Build alongside existing curricula or work in outside-of-school cntext

.footnote[[1]test]
---
# Thank you!

[**http://joshuamrosenberg.com**](http://joshuamrosenberg.com)

Slides created via the R package [**xaringan**](https://github.com/yihui/xaringan).

The chakra comes from [remark.js](https://remarkjs.com), [**knitr**](http://yihui.name/knitr), and [R Markdown](https://rmarkdown.rstudio.com).
